/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperatorLoginRouteImport } from './routes/operator-login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesBookingSystemCostRouteImport } from './routes/guides.booking-system-cost'
import { Route as GuidesDallasBookingSystemRouteImport } from './routes/guides.dallas-booking-system'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedConsoleBlipRouteImport } from './routes/_authenticated/console.blip'
import { Route as AuthenticatedConsoleCalendarRouteImport } from './routes/_authenticated/console.calendar'
import { Route as AuthenticatedConsoleClientsRouteImport } from './routes/_authenticated/console.clients'
import { Route as AuthenticatedConsoleLeadsRouteImport } from './routes/_authenticated/console.leads'
import { Route as AuthenticatedConsoleLinksRouteImport } from './routes/_authenticated/console.links'
import { Route as AuthenticatedConsolePlansRouteImport } from './routes/_authenticated/console.plans'
import { Route as AuthenticatedConsoleSettingsRouteImport } from './routes/_authenticated/console.settings'
import { Route as ApiPublicDailyMaintenanceRouteImport } from './routes/api/public/daily-maintenance'
import { Route as ApiPublicLeadIntakeRouteImport } from './routes/api/public/lead-intake'
import { Route as ApiPublicMessageWorkerRouteImport } from './routes/api/public/message-worker'
import { Route as ApiPublicSentWebhookRouteImport } from './routes/api/public/sent-webhook'
import { Route as ApiPublicStripeConnectCallbackRouteImport } from './routes/api/public/stripe-connect-callback'
import { Route as ApiPublicStripeConnectWebhookRouteImport } from './routes/api/public/stripe-connect-webhook'
import { Route as ApiPublicStripePlatformWebhookRouteImport } from './routes/api/public/stripe-platform-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorLoginRoute = OperatorLoginRouteImport.update({
  id: '/operator-login',
  path: '/operator-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesBookingSystemCostRoute = GuidesBookingSystemCostRouteImport.update({
  id: '/guides/booking-system-cost',
  path: '/guides/booking-system-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDallasBookingSystemRoute =
  GuidesDallasBookingSystemRouteImport.update({
    id: '/guides/dallas-booking-system',
    path: '/guides/dallas-booking-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleBlipRoute =
  AuthenticatedConsoleBlipRouteImport.update({
    id: '/blip',
    path: '/blip',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleCalendarRoute =
  AuthenticatedConsoleCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleClientsRoute =
  AuthenticatedConsoleClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleLeadsRoute =
  AuthenticatedConsoleLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleLinksRoute =
  AuthenticatedConsoleLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsolePlansRoute =
  AuthenticatedConsolePlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSettingsRoute =
  AuthenticatedConsoleSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const ApiPublicDailyMaintenanceRoute =
  ApiPublicDailyMaintenanceRouteImport.update({
    id: '/api/public/daily-maintenance',
    path: '/api/public/daily-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadIntakeRoute = ApiPublicLeadIntakeRouteImport.update({
  id: '/api/public/lead-intake',
  path: '/api/public/lead-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessageWorkerRoute = ApiPublicMessageWorkerRouteImport.update({
  id: '/api/public/message-worker',
  path: '/api/public/message-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSentWebhookRoute = ApiPublicSentWebhookRouteImport.update({
  id: '/api/public/sent-webhook',
  path: '/api/public/sent-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeConnectCallbackRoute =
  ApiPublicStripeConnectCallbackRouteImport.update({
    id: '/api/public/stripe-connect-callback',
    path: '/api/public/stripe-connect-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeConnectWebhookRoute =
  ApiPublicStripeConnectWebhookRouteImport.update({
    id: '/api/public/stripe-connect-webhook',
    path: '/api/public/stripe-connect-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripePlatformWebhookRoute =
  ApiPublicStripePlatformWebhookRouteImport.update({
    id: '/api/public/stripe-platform-webhook',
    path: '/api/public/stripe-platform-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operator-login': typeof OperatorLoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/guides/booking-system-cost': typeof GuidesBookingSystemCostRoute
  '/guides/dallas-booking-system': typeof GuidesDallasBookingSystemRoute
  '/guides/': typeof GuidesIndexRoute
  '/console/blip': typeof AuthenticatedConsoleBlipRoute
  '/console/calendar': typeof AuthenticatedConsoleCalendarRoute
  '/console/clients': typeof AuthenticatedConsoleClientsRoute
  '/console/leads': typeof AuthenticatedConsoleLeadsRoute
  '/console/links': typeof AuthenticatedConsoleLinksRoute
  '/console/plans': typeof AuthenticatedConsolePlansRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/api/public/daily-maintenance': typeof ApiPublicDailyMaintenanceRoute
  '/api/public/lead-intake': typeof ApiPublicLeadIntakeRoute
  '/api/public/message-worker': typeof ApiPublicMessageWorkerRoute
  '/api/public/sent-webhook': typeof ApiPublicSentWebhookRoute
  '/api/public/stripe-connect-callback': typeof ApiPublicStripeConnectCallbackRoute
  '/api/public/stripe-connect-webhook': typeof ApiPublicStripeConnectWebhookRoute
  '/api/public/stripe-platform-webhook': typeof ApiPublicStripePlatformWebhookRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operator-login': typeof OperatorLoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/guides/booking-system-cost': typeof GuidesBookingSystemCostRoute
  '/guides/dallas-booking-system': typeof GuidesDallasBookingSystemRoute
  '/guides': typeof GuidesIndexRoute
  '/console/blip': typeof AuthenticatedConsoleBlipRoute
  '/console/calendar': typeof AuthenticatedConsoleCalendarRoute
  '/console/clients': typeof AuthenticatedConsoleClientsRoute
  '/console/leads': typeof AuthenticatedConsoleLeadsRoute
  '/console/links': typeof AuthenticatedConsoleLinksRoute
  '/console/plans': typeof AuthenticatedConsolePlansRoute
  '/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/api/public/daily-maintenance': typeof ApiPublicDailyMaintenanceRoute
  '/api/public/lead-intake': typeof ApiPublicLeadIntakeRoute
  '/api/public/message-worker': typeof ApiPublicMessageWorkerRoute
  '/api/public/sent-webhook': typeof ApiPublicSentWebhookRoute
  '/api/public/stripe-connect-callback': typeof ApiPublicStripeConnectCallbackRoute
  '/api/public/stripe-connect-webhook': typeof ApiPublicStripeConnectWebhookRoute
  '/api/public/stripe-platform-webhook': typeof ApiPublicStripePlatformWebhookRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/operator-login': typeof OperatorLoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/guides/booking-system-cost': typeof GuidesBookingSystemCostRoute
  '/guides/dallas-booking-system': typeof GuidesDallasBookingSystemRoute
  '/guides/': typeof GuidesIndexRoute
  '/_authenticated/console/blip': typeof AuthenticatedConsoleBlipRoute
  '/_authenticated/console/calendar': typeof AuthenticatedConsoleCalendarRoute
  '/_authenticated/console/clients': typeof AuthenticatedConsoleClientsRoute
  '/_authenticated/console/leads': typeof AuthenticatedConsoleLeadsRoute
  '/_authenticated/console/links': typeof AuthenticatedConsoleLinksRoute
  '/_authenticated/console/plans': typeof AuthenticatedConsolePlansRoute
  '/_authenticated/console/settings': typeof AuthenticatedConsoleSettingsRoute
  '/api/public/daily-maintenance': typeof ApiPublicDailyMaintenanceRoute
  '/api/public/lead-intake': typeof ApiPublicLeadIntakeRoute
  '/api/public/message-worker': typeof ApiPublicMessageWorkerRoute
  '/api/public/sent-webhook': typeof ApiPublicSentWebhookRoute
  '/api/public/stripe-connect-callback': typeof ApiPublicStripeConnectCallbackRoute
  '/api/public/stripe-connect-webhook': typeof ApiPublicStripeConnectWebhookRoute
  '/api/public/stripe-platform-webhook': typeof ApiPublicStripePlatformWebhookRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operator-login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/console'
    | '/guides/booking-system-cost'
    | '/guides/dallas-booking-system'
    | '/guides/'
    | '/console/blip'
    | '/console/calendar'
    | '/console/clients'
    | '/console/leads'
    | '/console/links'
    | '/console/plans'
    | '/console/settings'
    | '/api/public/daily-maintenance'
    | '/api/public/lead-intake'
    | '/api/public/message-worker'
    | '/api/public/sent-webhook'
    | '/api/public/stripe-connect-callback'
    | '/api/public/stripe-connect-webhook'
    | '/api/public/stripe-platform-webhook'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/operator-login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/guides/booking-system-cost'
    | '/guides/dallas-booking-system'
    | '/guides'
    | '/console/blip'
    | '/console/calendar'
    | '/console/clients'
    | '/console/leads'
    | '/console/links'
    | '/console/plans'
    | '/console/settings'
    | '/api/public/daily-maintenance'
    | '/api/public/lead-intake'
    | '/api/public/message-worker'
    | '/api/public/sent-webhook'
    | '/api/public/stripe-connect-callback'
    | '/api/public/stripe-connect-webhook'
    | '/api/public/stripe-platform-webhook'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/operator-login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/console'
    | '/guides/booking-system-cost'
    | '/guides/dallas-booking-system'
    | '/guides/'
    | '/_authenticated/console/blip'
    | '/_authenticated/console/calendar'
    | '/_authenticated/console/clients'
    | '/_authenticated/console/leads'
    | '/_authenticated/console/links'
    | '/_authenticated/console/plans'
    | '/_authenticated/console/settings'
    | '/api/public/daily-maintenance'
    | '/api/public/lead-intake'
    | '/api/public/message-worker'
    | '/api/public/sent-webhook'
    | '/api/public/stripe-connect-callback'
    | '/api/public/stripe-connect-webhook'
    | '/api/public/stripe-platform-webhook'
    | '/_authenticated/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OperatorLoginRoute: typeof OperatorLoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  GuidesBookingSystemCostRoute: typeof GuidesBookingSystemCostRoute
  GuidesDallasBookingSystemRoute: typeof GuidesDallasBookingSystemRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiPublicDailyMaintenanceRoute: typeof ApiPublicDailyMaintenanceRoute
  ApiPublicLeadIntakeRoute: typeof ApiPublicLeadIntakeRoute
  ApiPublicMessageWorkerRoute: typeof ApiPublicMessageWorkerRoute
  ApiPublicSentWebhookRoute: typeof ApiPublicSentWebhookRoute
  ApiPublicStripeConnectCallbackRoute: typeof ApiPublicStripeConnectCallbackRoute
  ApiPublicStripeConnectWebhookRoute: typeof ApiPublicStripeConnectWebhookRoute
  ApiPublicStripePlatformWebhookRoute: typeof ApiPublicStripePlatformWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator-login': {
      id: '/operator-login'
      path: '/operator-login'
      fullPath: '/operator-login'
      preLoaderRoute: typeof OperatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/booking-system-cost': {
      id: '/guides/booking-system-cost'
      path: '/guides/booking-system-cost'
      fullPath: '/guides/booking-system-cost'
      preLoaderRoute: typeof GuidesBookingSystemCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/dallas-booking-system': {
      id: '/guides/dallas-booking-system'
      path: '/guides/dallas-booking-system'
      fullPath: '/guides/dallas-booking-system'
      preLoaderRoute: typeof GuidesDallasBookingSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/blip': {
      id: '/_authenticated/console/blip'
      path: '/blip'
      fullPath: '/console/blip'
      preLoaderRoute: typeof AuthenticatedConsoleBlipRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/calendar': {
      id: '/_authenticated/console/calendar'
      path: '/calendar'
      fullPath: '/console/calendar'
      preLoaderRoute: typeof AuthenticatedConsoleCalendarRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/clients': {
      id: '/_authenticated/console/clients'
      path: '/clients'
      fullPath: '/console/clients'
      preLoaderRoute: typeof AuthenticatedConsoleClientsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/leads': {
      id: '/_authenticated/console/leads'
      path: '/leads'
      fullPath: '/console/leads'
      preLoaderRoute: typeof AuthenticatedConsoleLeadsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/links': {
      id: '/_authenticated/console/links'
      path: '/links'
      fullPath: '/console/links'
      preLoaderRoute: typeof AuthenticatedConsoleLinksRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/plans': {
      id: '/_authenticated/console/plans'
      path: '/plans'
      fullPath: '/console/plans'
      preLoaderRoute: typeof AuthenticatedConsolePlansRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/settings': {
      id: '/_authenticated/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof AuthenticatedConsoleSettingsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/api/public/daily-maintenance': {
      id: '/api/public/daily-maintenance'
      path: '/api/public/daily-maintenance'
      fullPath: '/api/public/daily-maintenance'
      preLoaderRoute: typeof ApiPublicDailyMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-intake': {
      id: '/api/public/lead-intake'
      path: '/api/public/lead-intake'
      fullPath: '/api/public/lead-intake'
      preLoaderRoute: typeof ApiPublicLeadIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/message-worker': {
      id: '/api/public/message-worker'
      path: '/api/public/message-worker'
      fullPath: '/api/public/message-worker'
      preLoaderRoute: typeof ApiPublicMessageWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sent-webhook': {
      id: '/api/public/sent-webhook'
      path: '/api/public/sent-webhook'
      fullPath: '/api/public/sent-webhook'
      preLoaderRoute: typeof ApiPublicSentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-connect-callback': {
      id: '/api/public/stripe-connect-callback'
      path: '/api/public/stripe-connect-callback'
      fullPath: '/api/public/stripe-connect-callback'
      preLoaderRoute: typeof ApiPublicStripeConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-connect-webhook': {
      id: '/api/public/stripe-connect-webhook'
      path: '/api/public/stripe-connect-webhook'
      fullPath: '/api/public/stripe-connect-webhook'
      preLoaderRoute: typeof ApiPublicStripeConnectWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-platform-webhook': {
      id: '/api/public/stripe-platform-webhook'
      path: '/api/public/stripe-platform-webhook'
      fullPath: '/api/public/stripe-platform-webhook'
      preLoaderRoute: typeof ApiPublicStripePlatformWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleBlipRoute: typeof AuthenticatedConsoleBlipRoute
  AuthenticatedConsoleCalendarRoute: typeof AuthenticatedConsoleCalendarRoute
  AuthenticatedConsoleClientsRoute: typeof AuthenticatedConsoleClientsRoute
  AuthenticatedConsoleLeadsRoute: typeof AuthenticatedConsoleLeadsRoute
  AuthenticatedConsoleLinksRoute: typeof AuthenticatedConsoleLinksRoute
  AuthenticatedConsolePlansRoute: typeof AuthenticatedConsolePlansRoute
  AuthenticatedConsoleSettingsRoute: typeof AuthenticatedConsoleSettingsRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleBlipRoute: AuthenticatedConsoleBlipRoute,
  AuthenticatedConsoleCalendarRoute: AuthenticatedConsoleCalendarRoute,
  AuthenticatedConsoleClientsRoute: AuthenticatedConsoleClientsRoute,
  AuthenticatedConsoleLeadsRoute: AuthenticatedConsoleLeadsRoute,
  AuthenticatedConsoleLinksRoute: AuthenticatedConsoleLinksRoute,
  AuthenticatedConsolePlansRoute: AuthenticatedConsolePlansRoute,
  AuthenticatedConsoleSettingsRoute: AuthenticatedConsoleSettingsRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OperatorLoginRoute: OperatorLoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  GuidesBookingSystemCostRoute: GuidesBookingSystemCostRoute,
  GuidesDallasBookingSystemRoute: GuidesDallasBookingSystemRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiPublicDailyMaintenanceRoute: ApiPublicDailyMaintenanceRoute,
  ApiPublicLeadIntakeRoute: ApiPublicLeadIntakeRoute,
  ApiPublicMessageWorkerRoute: ApiPublicMessageWorkerRoute,
  ApiPublicSentWebhookRoute: ApiPublicSentWebhookRoute,
  ApiPublicStripeConnectCallbackRoute: ApiPublicStripeConnectCallbackRoute,
  ApiPublicStripeConnectWebhookRoute: ApiPublicStripeConnectWebhookRoute,
  ApiPublicStripePlatformWebhookRoute: ApiPublicStripePlatformWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
